CREATE TABLE Users (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Password VARCHAR(100) NOT NULL
);

CREATE TABLE Events (
  EventID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Date DATE NOT NULL,
  Time TIME NOT NULL,
  Venue VARCHAR(100) NOT NULL
);


CREATE TABLE Tickets (
  TicketID INT PRIMARY KEY AUTO_INCREMENT,
  EventID INT NOT NULL,
  SeatNumber VARCHAR(20) NOT NULL,
  Price DECIMAL(8, 2) NOT NULL,
  TicketType VARCHAR(50) NOT NULL,
  FOREIGN KEY (EventID) REFERENCES Events(EventID)
);


CREATE TABLE Bookings (
  BookingID INT PRIMARY KEY AUTO_INCREMENT,
  UserID INT NOT NULL,
  TicketID INT NOT NULL,
  BookingDate DATE NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID)
);

CREATE TABLE Payments (
  PaymentID INT PRIMARY KEY AUTO_INCREMENT,
  BookingID INT NOT NULL,
  PaymentMethod VARCHAR(50) NOT NULL,
  Amount DECIMAL(8, 2) NOT NULL,
  TransactionID VARCHAR(100) NOT NULL,
  FOREIGN KEY (BookingID) REFERENCES Bookings(BookingID)
);

CREATE TABLE Venues (
  VenueID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Address VARCHAR(200) NOT NULL,
  Capacity INT NOT NULL
);
